# Generated by Django 4.2.1 on 2023-06-02 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app_main', '0002_tag_remove_todoitem_todo_list_todoitem_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='created_date',
            new_name='timestamp',
        ),
    ]
