# Generated by Django 4.2.1 on 2023-06-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app_main', '0005_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='tags',
            field=models.ManyToManyField(to='todo_app_main.tag'),
        ),
    ]
