# Generated by Django 4.2.1 on 2023-06-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app_main', '0007_alter_todoitem_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='tags',
            field=models.ManyToManyField(blank=True, to='todo_app_main.tag'),
        ),
    ]
